inventory:
  hypervisors:
    vsphere:
      - name: 'lab'
        vcenter: '10.237.33.103'
        vsphere_username: 'sysadmin'
        vsphere_password: 'sysadmin'
output:
  target_api_url:
    hypervisors: 'https://storageapi.bellevuelab.isus.emc.com/storage/v1/array'
containers:
  vsphere: 'nctiggy/customer_collector_example'
